#region header

// Raven.Core - ISessionStore.cs
// 
// Alistair J. R. Young
// Arkane Systems
// 
// Copyright Arkane Systems 2012-2026.  All rights reserved.
// 
// Created: 2026-04-25 1:38 PM

#endregion

#region using

using JetBrains.Annotations;

#endregion

namespace ArkaneSystems.Raven.Core.Application.Sessions;

// The session store is the application's source of truth for the mapping between
// a client-visible session ID and a Foundry conversation ID.
//
// The two IDs are kept separate deliberately:
//   - SessionId  — generated by Raven.Core, handed to the client, stable across
//                  any future changes to the backing agent infrastructure.
//   - ConversationId — the identifier used internally to talk to the agent service
//                      (currently a Foundry AgentSession key). Clients never see this.
//
// This indirection means the agent backend can be swapped or the conversation
// recreated without invalidating the client's session handle.
public interface ISessionStore
{
  // Creates a new session record that links the given Foundry conversationId to a
  // freshly generated sessionId. Returns the new sessionId.
  Task<string> CreateSessionAsync (string conversationId);

  // Returns true if a session with the given sessionId exists in the store.
  Task<bool> SessionExistsAsync (string sessionId);

  // Looks up the internal Foundry conversationId for a given sessionId.
  // Also updates LastActivityAt as a side effect.
  // Returns null if the session does not exist.
  Task<string?> GetConversationIdAsync (string sessionId);

  // Returns session metadata (timestamps etc.) for display purposes.
  // Returns null if the session does not exist.
  Task<SessionInfo?> GetSessionAsync (string sessionId);

  // Removes the session record. Returns true if a record was deleted, false if
  // the sessionId was not found.
  Task<bool> DeleteSessionAsync (string sessionId);
}

public interface ISessionEventLog
{
  Task<SessionEventEnvelope> AppendAsync (string            sessionId,
                                          string            eventType,
                                          object            payload,
                                          string?           correlationId     = null,
                                          string?           userId            = null,
                                          CancellationToken cancellationToken = default);

  IAsyncEnumerable<SessionEventEnvelope> ReadAllAsync (string sessionId, CancellationToken cancellationToken = default);
}

public sealed record SessionEventEnvelope (
  string         EventId,
  string         SessionId,
  long           Sequence,
  string         EventType,
  DateTimeOffset OccurredAtUtc,
  string?        CorrelationId,
  string?        UserId,
  int            SchemaVersion,
  object         Payload);

// Application-layer value type carrying the metadata we hold about a session.
// Distinct from SessionInfoResponse (the HTTP contract) so the two can evolve
// independently.
public record SessionInfo (string SessionId, DateTimeOffset CreatedAt, DateTimeOffset? LastActivityAt);

// Snapshot of a session at a point in time. Used to fast-path session restore on
// server restart without replaying the full event log. Stored as a JSON file at
// {workspace}/sessions/snapshots/{sessionId}.snapshot.json.
//
// SchemaVersion guards forward compatibility — readers check this before
// attempting to deserialize known fields.
public record SessionSnapshot (
  string         SessionId,
  string         ConversationId,
  DateTimeOffset CreatedAt,
  DateTimeOffset? LastActivityAt,
  DateTimeOffset SnapshotAt,
  long           EventLogSequence,
  int            SchemaVersion = 1);

// Snapshot store: persists, loads, and invalidates session snapshots.
// Snapshots are written after every successful message so the most recent
// state is always recoverable without replaying the full event log.
//
// Invalidation removes the snapshot file; a missing file means "no valid
// snapshot" and the caller must fall back to event-log replay or create a
// fresh session.
public interface ISessionSnapshotStore
{
  // Atomically persist (or replace) the snapshot for the given session.
  Task SaveSnapshotAsync (SessionSnapshot snapshot, CancellationToken cancellationToken = default);

  // Load the latest snapshot for the given session, or null if none exists.
  Task<SessionSnapshot?> LoadSnapshotAsync (string sessionId, CancellationToken cancellationToken = default);

  // Delete the snapshot file for the given session. Returns true if a file
  // was removed, false if no snapshot was found (idempotent).
  Task<bool> InvalidateSnapshotAsync (string sessionId, CancellationToken cancellationToken = default);

  // Enumerate all stored snapshots in the snapshots directory.
  // Used by the client-facing session-list endpoint.
  IAsyncEnumerable<SessionSnapshot> ListSnapshotsAsync (CancellationToken cancellationToken = default);
}