namespace ArkaneSystems.Raven.Core.Infrastructure.Persistence;

// EF Core entity that maps to the "Sessions" table in raven.db.
// Each row records one client session and its link to the Foundry conversation.
public class SessionRecord
{
  // Client-facing identifier, generated by Raven.Core and handed to the console client.
  public string SessionId { get; set; } = string.Empty;

  // Internal identifier used to address the conversation with the agent service.
  // Not exposed to clients.
  public string ConversationId { get; set; } = string.Empty;

  // When the session was first created.
  public DateTimeOffset CreatedAt { get; set; }

  // Updated each time a message is sent through this session. Null until the
  // first message is processed.
  public DateTimeOffset? LastActivityAt { get; set; }
}